apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config
data:
  init.sql: |
    CREATE TABLE user_table
    (
        user_uuid  uuid primary key not null,
        login      varchar(256),
        password   varchar(256),
        first_name varchar(256),
        last_name  varchar(256),
        email      varchar(256),
        phone      varchar(256)
    );
    CREATE TABLE user_profile
    (
        user_uuid  uuid NOT NULL,
        avatar_uri varchar NULL,
        age        int2 NULL
    );
    CREATE TABLE orders
    (
        order_uuid   uuid primary key NOT NULL,
        product_uuid uuid             NOT NULL,
        quantity     int              NOT NULL,
        cost         int              NOT NULL,
        user_uuid    uuid             NOT NULL,
        user_email   varchar(255) NULL,
        success      int NULL,
        status       varchar(255)
    );
    CREATE TABLE storage
    (
        product_uuid       uuid NOT NULL,
        available_quantity int,
        reserved_quantity  int
    );
    INSERT INTO storage (product_uuid, available_quantity, reserved_quantity)
    VALUES ('22a214f1-8d88-4997-821e-a0781d003e16', 200, 0);
