apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config
data:
  init.sql: |
    create table user_table
    (
        user_uuid  uuid primary key not null,
        login      varchar(256),
        password   varchar(256),
        first_name varchar(256),
        last_name  varchar(256),
        email      varchar(256),
        phone      varchar(256)
    );
    create table user_profile
    (
        user_uuid  uuid    not null,
        avatar_uri varchar null,
        age        int2    null
    );
    create table storage
    (
        product_uuid       uuid             not null,
        name               varchar(255)     not null,
        price              double precision not null,
        available_quantity int,
        reserved_quantity  int
    );
    create table delivery
    (
        courier_uuid  uuid not null,
        is_available  bool,
        order_uuid    uuid,
        delivery_date timestamp,
        in_delivering boolean
    );
    create table orders
    (
        order_uuid    uuid primary key,
        product_uuid  uuid             not null,
        quantity      int              not null,
        cost          double precision not null,
        user_uuid     uuid             not null,
        user_email    varchar(255)     null,
        status        varchar(255),
        delivery_date timestamp        null
    );
    create table payment
    (
        user_uuid       uuid             not null,
        available_money double precision null,
        reserved_money  double precision null
    );
    create table notification
    (
        notification_uuid uuid         not null,
        email             varchar(255) not null,
        message           varchar(255) not null,
        order_uuid        uuid         not null,
        user_uuid         uuid         not null,
        is_notificated    boolean
    );
