apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config
data:
  init.sql: |
    create table if not exists user_table (
    id serial primary key,
    login varchar(256),
    password varchar(256),
    first_name varchar(256),
    last_name varchar(256),
    email varchar(256),
    phone varchar(256)
    );
    insert into user_table (login, password, first_name, last_name, email, phone)
    values
    ('osipovmr', '12345', 'ILYA', 'OSIPOV', 'osipovmr@yandex.ru', '+79112477069'),
    ('otus', '12345', 'John', 'Spilberg', 'otus@gmail.com', '8(812)6009812'),
    ('travel', '12345', 'Turkish', 'Airlines', 'fly@plane.sky', '00000');
