apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"