server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username:
    password:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yml
  jpa:
    hibernate.dll-auto: none
    show-sql: true
