apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config
data:
  init.sql: |
    CREATE TABLE public.user_profile
    (
        id         int8 NOT NULL,
        avatar_uri varchar NULL,
        age        int2 NULL
    );
