apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-postgresql-pvc
  labels:
    {{- include "app-db.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M