apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "notification.fullname" . }}
  labels:
    {{- include "notification.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: {{ .Values.service.name }}
      scrapeTimeout: 30s
      path: /actuator/prometheus
      honorLabels: true
      scheme: http
  namespaceSelector:
    matchNames:
      - project
  selector:
    matchLabels:
      {{- include "notification.selectorLabels" . | nindent 4 }}