apiVersion: v1
kind: ConfigMap
metadata:
  name: kuber-cm
data:
  application.yml: |
    server:
      port: 8000
    spring:
      datasource: 
        url: jdbc:postgresql://v1-db:5432/otus
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        jpa:
          show-sql: false
          hibernate:
            ddl-auto: none
    management:
      endpoint:
        health:
          show-details: always
      metrics:
        distribution:
          slo:
            http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms
      endpoints:
        web:
          exposure:
            include: "*"
      prometheus:
        metrics:
          export:
            enabled: true