apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-dp
  labels:
    name: kuber-dp
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name: app-container
          image: osipovmr/otus_homework:otus
          ports:
            - containerPort: 8000
