{
 "title": "Project",
 "description": "Мониторинг для итогового проекта",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "System CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "{{container}}" }
   ]
  },
  {
   "title": "JVM memory used bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(container) (jvm_memory_used_bytes)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Histogram_quantile 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/login\"}[1m])))",
     "legendFormat": "uri=\"/login\""
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/payment/checkAccount\"}[1m])))",
     "legendFormat": "uri=\"/payment/checkAccount\""
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/storage/product\"}[1m])))",
     "legendFormat": "uri=\"/storage/product\""
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/order/add\"}[1m])))",
     "legendFormat": "uri=\"/order/add\""
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/notification/{orderUUID}\"}[1m])))",
     "legendFormat": "uri=\"/notification/{orderUUID}\""
    }
   ]
  },
  {
   "title": "Histogram_quantile 0.50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/login\"}[1m])))",
     "legendFormat": "uri=\"/login\""
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/payment/checkAccount\"}[1m])))",
     "legendFormat": "uri=\"/payment/checkAccount\""
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/storage/product\"}[1m])))",
     "legendFormat": "uri=\"/storage/product\""
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/order/add\"}[1m])))",
     "legendFormat": "uri=\"/order/add\""
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/notification/{orderUUID}\"}[1m])))",
     "legendFormat": "uri=\"/notification/{orderUUID}\""
    }
   ]
  },
  {
   "title": "RPS",
   "type": "status-history",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\"}[5m])",
     "legendFormat": "{{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Kafka template count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_kafka_template_seconds_count",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Request count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/register\", status=\"201\"}",
     "legendFormat": "{{uri}} {{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{status=\"200\", uri=\"/order/add\"}",
     "legendFormat": "{{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Kafka listener count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (spring_kafka_listener_seconds_count{result=\"success\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/register\", status=\"201\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/register\", status=\"201\"}[1m])",
     "legendFormat": "uri=\"/register\", status=\"201\""
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/login\", status=\"200\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/login\", status=\"200\"}[1m])",
     "legendFormat": "uri=\"/login\", status=\"200\""
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/order/add\", status=\"200\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/order/add\", status=\"200\"}[1m])",
     "legendFormat": "uri=\"/order/add\", status=\"200\""
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/notification/{orderUUID}\", status=\"200\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/notification/{orderUUID}\", status=\"200\"}[1m])",
     "legendFormat": "uri=\"/notification/{orderUUID}\", status=\"200\""
    }
   ]
  }
 ]
}