apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-cm
data:
  kafka_properties.yml: |
    producer:
      propertiesMap:
        bootstrap.servers: kafka-controller-0.kafka-controller-headless.project.svc.cluster.local:9092
        client.id: storage-1
        group.id: storage
    consumer:
      propertiesMap:
        bootstrap.servers: kafka-controller-0.kafka-controller-headless.project.svc.cluster.local:9092
        client.id: storage-1
        group.id: storage

  application.yml: |
    logging:
      level:
        root: INFO
        org.springframework: INFO
        org.apache: OFF
        kafka: OFF
    properties:
      classpath: file:/config/
    server:
      port: 8000
    spring:
      datasource:
        url: jdbc:postgresql://v1-db.project:5432/otus
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        jpa:
          show-sql: false
          hibernate:
            ddl-auto: none
    management:
      endpoint:
        health:
          show-details: always
      metrics:
        distribution:
          slo:
            http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms
      endpoints:
        web:
          exposure:
            include: "*"
      prometheus:
        metrics:
          export:
            enabled: true