# Default values for otus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: osipovmr/otus_homework
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "kafka"

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

podAnnotations: { }

podSecurityContext: { }
# fsGroup: 2000



service:
  type: NodePort
  port: 8000
  targetPort: 8000
  name: super

ingress:
  enabled: true
  className: "nginx"
  annotations: {
    nginx.ingress.kubernetes.io/auth-url: "http://v2-auth.project.svc.cluster.local:8000/auth",
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/signin",
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User,X-Email,X-UserId,X-First-Name,X-Last-Name"
  }
  hosts:
    - host: arch.homework
      paths:
        - path: /users/me
          pathType: Prefix
        - path: /order/add
          pathType: Prefix
        - path: /kafka
          pathType: Prefix

