apiVersion: v1
kind: Pod
metadata:
  name: app-kuber
  labels:
    env: prod
spec:
  containers:
    - name: app-kuber-container
      image: osipovmr/otus_homework:helm
      ports:
        - containerPort: 8000
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: kuber-secret
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kuber-secret
              key: db-password
