apiVersion: v1
kind: Pod
metadata:
  name: app-kuber
  labels:
    env: prod
spec:
  containers:
    - name: app-kuber-container
      image: osipovmr/otus_homework:otus
      ports:
        - containerPort: 8000
