apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "delivery.fullname" . }}
  labels:
    {{- include "delivery.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: {{ .Values.service.name }}
      scrapeTimeout: 30s
      path: /actuator/prometheus
      honorLabels: true
      scheme: http
  namespaceSelector:
    matchNames:
      - project
  selector:
    matchLabels:
      {{- include "delivery.selectorLabels" . | nindent 4 }}